services:
  - type: web
    name: payment-screenshot-maker
    env: python
    buildCommand: apt-get update && apt-get install -y libpango-1.0-0 && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10